### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array, integer given in ...

### ISSUE THREAD

**Issue by MioVisman** [artoodetoo/container#3]
Тестировал метод getParameter(). Вероятно аналогичная ошибка будет в методе setParameter().
Тесты с другими вариантами проверок (`is_array() + array_key_exists()` и `isset() + is_array() + array_key_exists()` <- это вариант быстрее, особенно на 5.6.x):
1. Нормальное поведение, элемент отличный от null - http://sandbox.onlinephpfunctions.com/code/7219247d1584531490acdb5be4ac71015d17ca28
2. Нормальное поведение, элемент равен null - http://sandbox.onlinephpfunctions.com/code/0acde0551d609bc028096f389e8e4b858f44aa6b
3. Поведение с ошибкой, элемент не null - http://sandbox.onlinephpfunctions.com/code/d2ae6641b87c95b3e0bca00bb3e04fd4b27c7fe6
4. Поведение с ошибкой, элемент null - http://sandbox.onlinephpfunctions.com/code/479e0f1f8d82535cefada8107c17726e83e3cad9

**Comment by artoodetoo** [comment]
Спасибо!

**Comment by artoodetoo** [comment]
Я принимаю изменения по твоему варианту №2:
```
        foreach ($segments as $s) {
            if (!is_array($ptr) || !array_key_exists($s, $ptr)) {
                return $default;
            }
            $ptr =& $ptr[$s];
        }

```
Правда у меня есть сомнения, может быть подобную ситуацию с отсутствием запрашиваемого пути надо считать критической ошибкой?

**Comment by MioVisman** [comment]
>может быть подобную ситуацию с отсутствием запрашиваемого пути надо считать критической ошибкой?

У тебя там изначально $default задуман, так что это не ошибка.

P.S. И 3-й вариант быстрее 2-го второго даже на 7.0.5 ;)

**Comment by artoodetoo** [comment]
$default да, про слона я забыл. Второй выглядит лучше :)

Вроде бы третий вариант можно заменить на простой isset($ptr[$s]) разве нет? То что после "или" фактически возвращает то же самое.

**Comment by MioVisman** [comment]
После или - `(is_array($ptr) && array_key_exists($s, $ptr))` добавлено для значений `null`. Если этой проверки не будет, то `isset()` вернет `false`.

**Comment by artoodetoo** [comment]
null это эквивалент "не задано". так что проверки isset достаточно, на мой взгляд.

**Comment by artoodetoo** [comment]
С дополнительной проверкой мы добъемся того, что можно будет получить пустое значение. Без этой проверки будет считаться, что значение не задано и вернётся null. Масло масляное.

**Comment by MioVisman** [comment]
А если $default будет задан отличным от `null`, а значение параметра будет `null`? Правда реален ли такой вариант!?

**Comment by artoodetoo** [comment]
Мне кажется это на 100% синтетический случай. :) Практика такова, что почти всегда указание null в качестве параметра имеет тот же эффект, что и неуказание этого параметра вообще. Это _интуитивно ожидаемое поведение_. Встроенная в язык конструкция isset() также считает равнозначными случаи когда переменная не задана и когда она равна null.

**Comment by artoodetoo** [comment]
Если таки считать null нормальным значением, то класс Container следует дополнить методом unsetParameter(), иначе непонятно как стереть значение. А мне очень не хочется раздувать этот класс.

**Comment by MioVisman** [comment]
В таком случае следует только isset() использовать для проверки.
