### ISSUE TITLE
Передавать контейнер прямо в конструктор

### ISSUE THREAD

**Issue by MioVisman** [artoodetoo/container#5]
Я все успокоится не могу :)
Предлагаю ссылку на контейнер передавать не через метод setContainer(), а прямо в конструктор.
Заменяем

    $service = new $class(...$args);
    if ($service instanceof ContainerAwareInterface) {
        $service->setContainer($this);
    }

на

    $args[] = $this; // передача контейнера сразу в конструктор
    $service = new $class(...$args);

В результате избавляемся от не нужного метода setContainer() (и маленькой кучки дополнительной писанины) и получаем ссылку сразу в конструкторе созданного класса.

А если контейнер в классе не нужен, то в аргументах __construct() не задаем последний аргумент для него.

**Comment by artoodetoo** [comment]
Ну если тебе удобно инжектить контейнер через конструтор, инжекти, почему бы нет. Только   

1. интерфейс ContainerAwareInterface здесь не при чём, я считаю. пусть он остаётся сам по себе.
2. как будет выглядеть описание сервисов в конфигурации с этим нововведением? например в конфиге описано, что в конструктор передается два параметра, а на самом деле их будет передаваться три? некрасиво, на мой взгляд.

**Comment by artoodetoo** [comment]
Но ты навёл меня на мысль, что было бы неплохо контейнеру иметь ссылку на себя чтобы иметь возможность вставить её в параметры. Типа:
```php
class Container implements ContainerInterface
{
    private $instances = [];
    private $config = [ 'shared' => [], 'multiple'  => [] ];

    public function __construct(array $config = null)
    {
        $this->config['CONTAINER'] = $this;
        if (!empty($config)) {
            $this->config($config);
        }
    }
...
```
и в конфиге
```php
$config = [
  ...
  'shared' => [
    'myService' => [
      'class' => Foo\Bar\Baz::class,
      'cache'     => '%ROOT%/cache',
      'container' => '%CONTAINER%',
    ],
    ...
  ]
];
```

---

**P.S.** сказано-сделано: 23cc372

Полный пример использования само-ссылки:
```php
<?php

require __DIR__.'/../vendor/autoload.php';

use R2\DependencyInjection\Container;

class Example
{
    private $container;

    public function __construct($container)
    {
        $this->container = $container;
    }

    public function render($name)
    {
        echo $this->container->getParameter($name);
    }
}


$config = [
  'xx' => [
    'yy' => 123,
  ],
  'shared' => [
    'example' => [
        'class' => Example::class,
        'container' => '%CONTAINER%',
    ],
  ]
];
$c = new Container($config);
$c->get('example')->render('xx.yy');
```

**Comment by MioVisman** [comment]
Этим исправлением откатил Fix #4 до первоначального состояния.

**Comment by artoodetoo** [comment]
Oops! fixed.
Прикольная штука git. Можно создать альтернативную историю. Вроде бы и старые коммиты есть где-то в репозитории, ссылки на них работают, но глядя в git log об этом не догадываешся. 

Текущее состояние: a48bce4
